# This file contains values from Cookiecutter

default_context:
  project_name: "glomerulus-detection"
  project_description: "Awesome `glomerulus-detection` is a Python cli/package created with https://github.com/Undertone0809/python-package-template"
  organization: "mosoriob"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "mosoriob"
  email: "maxiosorio@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
